version: '3.8'

services:
  airplay-discord:
    image: ghcr.io/warpflow-home/airplay-discord:latest
    networks:
      - hostnet
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - VOICE_CHANNEL_ID=${VOICE_CHANNEL_ID}
    deploy:
      placement:
        constraints:
          - node.hostname == node01

networks:
  hostnet:
    name: host
    external: true