version: '3.8'

services:
  airplay-discord:
    image: ghcr.io/warpflow-home/airplay-discord:latest
    networks:
      - hostnet
    volumes:
      - /var/run/dbus:/var/run/dbus
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - VOICE_CHANNEL_ID=${VOICE_CHANNEL_ID}
    deploy:
      replicas: 1